name: sync-code

on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.repository == 'shitouer0515/voshell'
    timeout-minutes: 2

    steps:
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y
        sudo -E apt-get install -y build-essential git git-core curl wget
        sudo -E apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'

    - name: Prepare
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.EVINEKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com > ~/.ssh/known_hosts

    - name: Clone
      run: |
        git clone -b master git@gitee.com:evine/jd_shell.git jd_shell

    - name: Push code
      uses: ad-m/github-push-action@master
      with:
        directory: jd_shell
        github_token: ${{ secrets.SYNC }}
        branch: master

    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 0
